name: Daily Telegram Ingestion

on:
  schedule:
    - cron: '0 0 * * *'  # Every 24 hours at 00:00 UTC
  workflow_dispatch:     # Optional manual trigger

jobs:
  run-daily-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run ingestion pipeline
        run: |
          python path/to/your/pipeline.py
